import { IRating } from "@/types/interfaces";

export const ratings: IRating[] = [
  {
    id: 1,
    user_id: 101,
    artisan_id: 1,
    score: 4,
    avis: "Très satisfait du travail de la Menuiserie Dupont. Les meubles sur mesure sont de grande qualité.",
    created_at: new Date("2023-07-12T08:30:00"),
    last_update: new Date(),
  },
  {
    id: 2,
    user_id: 102,
    artisan_id: 2,
    score: 5,
    avis: "Excellent service de la Scierie Martin. Le bois de chauffage est de première qualité.",
    created_at: new Date("2023-08-05T14:45:00"),
    last_update: new Date(),
  },
  {
    id: 3,
    user_id: 103,
    artisan_id: 3,
    score: 2,
    avis: "L'Atelier Bois et Fer n'a pas répondu à mes attentes. La qualité ne correspond pas au prix payé.",
    created_at: new Date("2023-09-20T10:15:00"),
    last_update: new Date(),
  },
  {
    id: 4,
    user_id: 104,
    artisan_id: 4,
    score: 3,
    avis: "Ébénisterie Leclerc a fait du bon travail, mais le délai de livraison était un peu long.",
    created_at: new Date("2023-10-02T18:00:00"),
    last_update: new Date(),
  },
  {
    id: 5,
    user_id: 105,
    artisan_id: 5,
    score: 1,
    avis: "Artisan Jardinier a laissé mon jardin dans un état pire qu'avant. Mauvaise expérience globale.",
    created_at: new Date("2023-11-15T12:30:00"),
    last_update: new Date(),
  },
  {
    id: 6,
    user_id: 106,
    artisan_id: 1,
    score: 4,
    avis: "La Menuiserie Dupont a bien répondu à mes attentes en termes de design et de qualité de fabrication.",
    created_at: new Date("2023-12-10T09:45:00"),
    last_update: new Date(),
  },
  {
    id: 7,
    user_id: 107,
    artisan_id: 3,
    score: 5,
    avis: "L'Atelier Bois et Fer a créé une œuvre d'art unique pour ma maison. Vraiment impressionné par leur savoir-faire.",
    created_at: new Date("2023-01-25T15:20:00"),
    last_update: new Date(),
  },
  {
    id: 8,
    user_id: 108,
    artisan_id: 2,
    score: 3,
    avis: "Scierie Martin propose des produits de qualité, mais le service client pourrait être amélioré.",
    created_at: new Date("2023-02-08T17:00:00"),
    last_update: new Date(),
  },
  {
    id: 9,
    user_id: 109,
    artisan_id: 4,
    score: 4,
    avis: "Ébénisterie Leclerc a restauré avec soin un vieux meuble familial. Ravi du résultat final.",
    created_at: new Date("2023-03-15T11:10:00"),
    last_update: new Date(),
  },
  {
    id: 10,
    user_id: 110,
    artisan_id: 5,
    score: 2,
    avis: "Artisan Jardinier a créé un désastre dans mon jardin. Mauvaise planification et mauvaise exécution.",
    created_at: new Date("2023-04-05T13:55:00"),
    last_update: new Date(),
  },
  {
    id: 11,
    user_id: 119,
    artisan_id: 1,
    score: 5,
    avis: "La Menuiserie Dupont a créé une cuisine sur mesure pour moi. Les détails et la finition sont impeccables.",
    created_at: new Date("2023-06-20T10:00:00"),
    last_update: new Date(),
  },
  {
    id: 12,
    user_id: 120,
    artisan_id: 1,
    score: 3,
    avis: "La qualité du bois utilisé par la Menuiserie Dupont est excellente, mais le service client pourrait être amélioré.",
    created_at: new Date("2023-07-05T13:30:00"),
    last_update: new Date(),
  },
  {
    id: 13,
    user_id: 121,
    artisan_id: 1,
    score: 4,
    avis: "Menuiserie Dupont a conçu un meuble de salle de bains élégant. Je suis satisfait du résultat final.",
    created_at: new Date("2023-08-01T09:45:00"),
    last_update: new Date(),
  },
  {
    id: 14,
    user_id: 122,
    artisan_id: 1,
    score: 2,
    avis: "La Menuiserie Dupont a pris du retard dans la livraison de mon projet, ce qui a été très inconfortable pour moi.",
    created_at: new Date("2023-08-20T16:15:00"),
    last_update: new Date(),
  },
  {
    id: 15,
    user_id: 123,
    artisan_id: 1,
    score: 5,
    avis: "Très content du service de la Menuiserie Dupont. Les meubles sont durables et bien fabriqués.",
    created_at: new Date("2023-09-10T11:30:00"),
    last_update: new Date(),
  },
  {
    id: 16,
    user_id: 124,
    artisan_id: 2,
    score: 4,
    avis: "Scierie Martin propose un large choix de bois. J'ai trouvé exactement ce dont j'avais besoin pour mon projet.",
    created_at: new Date("2023-09-25T14:00:00"),
    last_update: new Date(),
  },
  {
    id: 17,
    user_id: 125,
    artisan_id: 2,
    score: 3,
    avis: "Le bois livré par Scierie Martin était de bonne qualité, mais la communication pourrait être améliorée.",
    created_at: new Date("2023-10-15T10:30:00"),
    last_update: new Date(),
  },
  {
    id: 18,
    user_id: 126,
    artisan_id: 2,
    score: 5,
    avis: "Scierie Martin m'a fourni du bois de chauffage qui a bien fonctionné. Service rapide et efficace.",
    created_at: new Date("2023-11-05T13:45:00"),
    last_update: new Date(),
  },
  {
    id: 19,
    user_id: 127,
    artisan_id: 2,
    score: 2,
    avis: "J'ai eu des problèmes de livraison avec Scierie Martin. Le bois est arrivé en retard, ce qui a causé des inconvénients.",
    created_at: new Date("2023-11-25T15:15:00"),
    last_update: new Date(),
  },
  {
    id: 20,
    user_id: 128,
    artisan_id: 2,
    score: 4,
    avis: "Scierie Martin a répondu rapidement à mes questions et a fourni des conseils utiles. Bon service client.",
    created_at: new Date("2023-12-10T09:00:00"),
    last_update: new Date(),
  },
  {
    id: 22,
    user_id: 129,
    artisan_id: 3,
    score: 5,
    avis: "Atelier Bois et Fer a créé une magnifique table en bois pour mon salon. Un travail artisanal exceptionnel.",
    created_at: new Date("2023-01-15T12:30:00"),
    last_update: new Date(),
  },
  {
    id: 23,
    user_id: 130,
    artisan_id: 3,
    score: 4,
    avis: "J'ai commandé une étagère sur mesure chez Atelier Bois et Fer. Le résultat est élégant et bien conçu.",
    created_at: new Date("2023-02-01T14:45:00"),
    last_update: new Date(),
  },
  {
    id: 24,
    user_id: 131,
    artisan_id: 3,
    score: 2,
    avis: "L'Atelier Bois et Fer a pris du retard dans la réalisation de mon projet. La communication pourrait être améliorée.",
    created_at: new Date("2023-02-20T09:00:00"),
    last_update: new Date(),
  },
  {
    id: 25,
    user_id: 132,
    artisan_id: 3,
    score: 5,
    avis: "Très satisfait du service d'Atelier Bois et Fer. Leur équipe est talentueuse et créative.",
    created_at: new Date("2023-03-10T11:15:00"),
    last_update: new Date(),
  },
  {
    id: 27,
    user_id: 133,
    artisan_id: 4,
    score: 4,
    avis: "Ébénisterie Leclerc a restauré une vieille commode pour moi. Le résultat est impressionnant.",
    created_at: new Date("2023-03-25T14:30:00"),
    last_update: new Date(),
  },
  {
    id: 28,
    user_id: 134,
    artisan_id: 4,
    score: 3,
    avis: "Bon travail d'Ébénisterie Leclerc, mais le coût de la restauration était un peu élevé à mon goût.",
    created_at: new Date("2023-04-10T10:45:00"),
    last_update: new Date(),
  },
  {
    id: 29,
    user_id: 135,
    artisan_id: 4,
    score: 2,
    avis: "La communication avec Ébénisterie Leclerc était difficile. Ils ne répondaient pas toujours à mes appels.",
    created_at: new Date("2023-04-25T12:00:00"),
    last_update: new Date(),
  },
  {
    id: 30,
    user_id: 136,
    artisan_id: 4,
    score: 5,
    avis: "Ébénisterie Leclerc a créé une magnifique armoire sur mesure pour ma chambre. La qualité est excellente.",
    created_at: new Date("2023-05-10T09:15:00"),
    last_update: new Date(),
  },
  {
    id: 32,
    user_id: 137,
    artisan_id: 5,
    score: 3,
    avis: "Artisan Jardinier a fait un bon travail d'entretien de mon jardin. Cependant, quelques plantes ont été endommagées.",
    created_at: new Date("2023-05-25T11:30:00"),
    last_update: new Date(),
  },
  {
    id: 33,
    user_id: 138,
    artisan_id: 5,
    score: 1,
    avis: "Mauvaise expérience avec Artisan Jardinier. Ils ont coupé les mauvaises branches de mon arbre, le laissant en mauvais état.",
    created_at: new Date("2023-06-10T13:45:00"),
    last_update: new Date(),
  },
  {
    id: 34,
    user_id: 139,
    artisan_id: 5,
    score: 4,
    avis: "Artisan Jardinier a fait un excellent travail d'aménagement paysager devant ma maison. C'est maintenant très accueillant.",
    created_at: new Date("2023-06-25T15:00:00"),
    last_update: new Date(),
  },
  {
    id: 35,
    user_id: 140,
    artisan_id: 5,
    score: 2,
    avis: "Déçu par le service d'Artisan Jardinier. Le résultat final ne correspondait pas à mes attentes.",
    created_at: new Date("2023-07-10T09:30:00"),
    last_update: new Date(),
  },
];
